In [1]:
# Importing the neccesary libraries 
import numpy as np 

In [2]:
class Matrix_here(object):
    def __init__(self,column, row):
        self.columnSize = column
        self.rowSize = row
    def insertValues(self):
        print("Enter inputs for the matrices ")
        tuple_c = (self.columnSize,self.rowSize)
        list_c = []
        i = 0
        while i != self.rowSize:
            j = 0
            while j != self.columnSize:
                try:
                    inp = int(input("Enter "))
                except:
                    print("Error 3 : Error in input")
                list_c.append(inp)
                j+= 1
            i+= 1
        a = np.array(list_c)
        self.array_One = np.reshape(a,tuple_c)
        print(self.array_One)
        return self.array_One
    def addition(self,b):
        try:
            c = self.array_One+b
            return c
        except:
            print("Error 1 : Couldnt add matrices , maybe their dimensions dont match")
    
    def subtaction(self,b):
        try:
            c = self.array_One-b
            return c
        except:
            print("Error 1 : Couldnt subtract matrices , maybe their dimensions dont match")
    
    def scalarMultiplication(self,scalar):
        try:
            c = self.array_One*scalar
            return c
        except: 
            print("Error 2: Maybe the value u sent is not the required type ")
    def elementWiseMatrixMultiplication(self,b):
        try:
            c = self.array_One*b
            return c
        except: 
            print("Error 1: Maybe Dimension Mismatch")
    def MatrixMultiplication(self,b):
        try:
            c = self.array_One.dot(b)
            return c
        except: 
            print("Error 1: Maybe Dimension Mismatch")
    def Transpose(self):
        try:
            c = self.array_One.transpose()
            return c
        except: 
            print("Error 4 ")
    def FindTrace(self):
        try:
            c = self.array_One.trace()
            return c
        except: 
            print("Error 4 ")
    def SolveLinearEquation(self , input , output):
        try:
            solution = np.linalg.solve(input,output)
            return solution
        except: 
            print("Error 6: Either the dimensions are incorrect , or the matrix is singular ")
    def FindDeterminant(self):
        try:
            solution = np.linalg.det(self.array_One)
            return solution
        except: 
            print("Error 4 ")
    def FindInverse(self):
        try:
            solution = np.linalg.inv(self.array_One)
            return solution
        except: 
            print("Error 4 ")
    def FindSVD(self):
        try:
            solution = np.linalg.svd(self.array_One)
            return solution
        except: 
            print("Error 4 ")
    def FindEigenValue(self):
        try:
            solution = np.linalg.eigvals(self.array_One)
            return solution
        except: 
            print("Error 8 : The eigen value computation foes not converge  ")
    def SearchForElement(self,searchElement):
        try:
            c = np.where(self.array_One == searchElement)
            return c
        except:
            print("Error 4")
    def getDiffImSum(self):
        try:
            upper = np.triu(self.array_One)
            sum_Upper = np.sum(upper)
            lower = np.triu(self.array_One)
            sum_lower = np.sum(lower)
            diff = sum_Upper - sum_lower
            return diff
        except:
            print("Error 4")



    

In [3]:
Matrix1 = Matrix_here(3,3)
Matrix2 = Matrix_here(3,3)
A = Matrix1.insertValues()
B = Matrix2.insertValues()

Enter inputs for the matrices 
[[ 1  1 11]
 [11  1  1]
 [11 12  3]]
Enter inputs for the matrices 
[[ 4  1  2]
 [ 3  4  2]
 [12  3  4]]


In [120]:
val =  Matrix1.addition(B)
print(val)

[[ 24  14  15]
 [243   5 227]
 [ 67   8  69]]


In [121]:
val = Matrix1.subtaction(B)
print(val)

[[ -22    8    7]
 [-221   -1  219]
 [   1   -2  -65]]


In [122]:
val = Matrix1.scalarMultiplication(5)
print(val)

[[   5   55   55]
 [  55   10 1115]
 [ 170   15   10]]


In [123]:
val = Matrix1.elementWiseMatrixMultiplication(B)
print(val)

[[  23   33   44]
 [2552    6  892]
 [1122   15  134]]


In [124]:
val = Matrix1.MatrixMultiplication(B)
print(val)

[[ 2938    91   785]
 [ 8076  1154 14993]
 [ 1544   121   282]]


In [125]:
val = Matrix1.Transpose()
print(val)

[[  1  11  34]
 [ 11   2   3]
 [ 11 223   2]]


In [126]:
val = Matrix1.FindTrace()
print(val)

5


In [127]:
val = Matrix1.c
np.linalg.solve(A,B)

array([[ 0.82182438,  0.12413835,  1.95178419],
       [ 1.02557545,  0.25641213,  0.2669346 ],
       [ 0.99062234,  0.00502984, -0.08073316]])

In [128]:
val = np.where(A == 1000 )
print(val)

(array([], dtype=int64), array([], dtype=int64))


In [129]:
d = np.triu(A)
print(d)
val = np.sum(d)
l = np.tril(A)
val2 = np.sum(l)
print(l)
print(val-val2)

[[  1  11  11]
 [  0   2 223]
 [  0   0   2]]
[[ 1  0  0]
 [11  2  0]
 [34  3  2]]
197


In [30]:
c = np.where(A == 1)
print(c)

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 1, 2], dtype=int64))


In [33]:
column_no = np.array2string(c[0])
row_no = np.array2string(c[1])

t_w = column_no.split("[")
t_w = t_w[1].split("]")
column_no = t_w[0]
print("Corresponding Column no :",column_no)
t_w = row_no.split("[")
t_w = t_w[1].split("]")
row_no = t_w[0]
if(len(row_no)<1):
    print("Element not present ")
print("Corresponding Row no    :",row_no)

Corresponding Column no : 0 0 1 1
Corresponding Row no    : 0 1 1 2
